### PR TITLE
restservice: change requirements versions

### PR DESCRIPTION
**Pull request by tehasdf**
(some of) those are the versions of things that we have on master as well
Those should make the rpms not require LIBFFI_CLOSURE, whatever that is

### CODE REVIEW

**Comment by tehasdf** [comment]
restservice
```
[2021-12-08T16:18:36.568Z] Requires: /bin/bash /opt/manager/env/bin/python3 /usr/bin/env ld-linux-x86-64.so.2()(64bit) ld-linux-x86-64.so.2(GLIBC_2.3)(64bit) libc.so.6()(64bit) libc.so.6(GLIBC_2.13)(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.15)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.3.2)(64bit) libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.4)(64bit) libc.so.6(GLIBC_2.6)(64bit) libc.so.6(GLIBC_2.7)(64bit) libdbus-1.so.3()(64bit) libdbus-glib-1.so.2()(64bit) libffi-c643fa1a.so.6.0.4()(64bit) libglib-2.0.so.0()(64bit) libgobject-2.0.so.0()(64bit) libpq.so.5()(64bit) libpthread.so.0()(64bit) libpthread.so.0(GLIBC_2.2.5)(64bit) libpython3.6m.so.1.0()(64bit) rtld(GNU_HASH)
```

**Comment by tehasdf** [comment]
mgmtworker
```


[2021-12-08T16:20:21.392Z] Requires: /bin/bash /opt/mgmtworker/env/bin/python3 /usr/bin/env ld-linux-x86-64.so.2()(64bit) ld-linux-x86-64.so.2(GLIBC_2.3)(64bit) libc.so.6()(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.15)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.3.2)(64bit) libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.4)(64bit) libc.so.6(GLIBC_2.7)(64bit) libc.so.6(GLIBC_2.8)(64bit) libcom_err.so.2()(64bit) libffi-d58a691e.so.8.1.0()(64bit) libffi-d58a691e.so.8.1.0(LIBFFI_BASE_8.0)(64bit) libffi-d58a691e.so.8.1.0(LIBFFI_CLOSURE_8.0)(64bit) libgssapi_krb5.so.2()(64bit) libgssapi_krb5.so.2(gssapi_krb5_2_MIT)(64bit) libk5crypto.so.3()(64bit) libkrb5.so.3()(64bit) libkrb5.so.3(krb5_3_MIT)(64bit) libpq.so.5()(64bit) libpthread.so.0()(64bit) libpthread.so.0(GLIBC_2.2.5)(64bit) libpython3.6m.so.1.0()(64bit) rtld(GNU_HASH)
```

**Comment by tehasdf** [comment]
I think the main point is the more-up-to-date version of cffi

**Comment by tehasdf** [comment]
Restservice requires
```
[2021-12-08T17:14:44.740Z] Requires: /bin/bash
[/opt/manager/env/bin/python3 /usr/bin/env ld-linux-x86-64.so.2()(64bit)
[ld-linux-x86-64.so.2(GLIBC_2.3)(64bit) libc.so.6()(64bit)
[libc.so.6(GLIBC_2.13)(64bit) libc.so.6(GLIBC_2.14)(64bit)
[libc.so.6(GLIBC_2.15)(64bit) libc.so.6(GLIBC_2.2.5)(64bit)
[libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.3.2)(64bit)
[libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.4)(64bit)
[libc.so.6(GLIBC_2.6)(64bit) libc.so.6(GLIBC_2.7)(64bit)
[libdbus-1.so.3()(64bit) libdbus-glib-1.so.2()(64bit)
[libffi-c643fa1a.so.6.0.4()(64bit) libglib-2.0.so.0()(64bit)
[libgobject-2.0.so.0()(64bit) libpq.so.5()(64bit)
[libpthread.so.0()(64bit) libpthread.so.0(GLIBC_2.2.5)(64bit)
[libpython3.6m.so.1.0()(64bit) rtld(GNU_HASH)
```

**Review by mateumann — APPROVED** [review]

**Comment by tehasdf** [comment]
Mgmtworker requires
```
[2021-12-08T17:16:50.632Z] Requires: /bin/bash
[/opt/mgmtworker/env/bin/python3 /usr/bin/env
[ld-linux-x86-64.so.2()(64bit) ld-linux-x86-64.so.2(GLIBC_2.3)(64bit)
[libc.so.6()(64bit) libc.so.6(GLIBC_2.14)(64bit)
[libc.so.6(GLIBC_2.15)(64bit) libc.so.6(GLIBC_2.2.5)(64bit)
[libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.3.2)(64bit)
[libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.4)(64bit)
[libc.so.6(GLIBC_2.7)(64bit) libc.so.6(GLIBC_2.8)(64bit)
[libcom_err.so.2()(64bit) libffi-c643fa1a.so.6.0.4()(64bit)
[libgssapi_krb5.so.2()(64bit)
[libgssapi_krb5.so.2(gssapi_krb5_2_MIT)(64bit) libk5crypto.so.3()(64bit)
[libkrb5.so.3()(64bit) libkrb5.so.3(krb5_3_MIT)(64bit)
[libpq.so.5()(64bit) libpthread.so.0()(64bit)
[libpthread.so.0(GLIBC_2.2.5)(64bit) libpython3.6m.so.1.0()(64bit)
[rtld(GNU_HASH)
```

**Pull request merged**
