### PR TITLE
RD-6168 Don't test py36-based source plugin

### PR DESCRIPTION
**Pull request by mateumann**
... it is not compatible with Python 3.10

### CODE REVIEW

**Comment by geokala** [comment]
We do still need to be able to support 3.6 based source plugins though, somehow.

**Comment by tehasdf** [comment]
@geokala I don't easily see how. Source plugins can't declare what's their required python version (unlike managed plugins)

**Comment by geokala** [comment]
Source plugins are somewhat legacy. We should perhaps default to it py3.6 unless $something?

**Comment by tehasdf** [comment]
Eh, that's kinda silly.

I mean, python packages CAN say in setup.py what version do they want, so perhaps we'll want some parsing of it eventually. But source plugins are so rarely used that I thought it's not worth the effort (yet)

**Comment by geokala** [comment]
In that case let's just default source plugins to 3.6 so that they keep working.

**Comment by tehasdf** [comment]
That makes new source plugins not work, then. (3.10-only ones)

**Review by tehasdf — APPROVED** [review]
OK, this is to some degree removing a "feature", but let's do this for now. If we want to, we can revert this after RD-6196

**Pull request merged**
